"""add_dob_to_ia_models

Revision ID: 596a3d687fbe
Revises: d2ba705a30b4
Create Date: 2026-03-12 15:01:25.930922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '596a3d687fbe'
down_revision: Union[str, Sequence[str], None] = 'd2ba705a30b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Sanitized: Removed business tables belonging to tenant silo.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Sanitized: Removed business tables belonging to tenant silo.
    pass
    # ### end Alembic commands ###
