"""add_ia_master_to_master

Revision ID: 670e34926f85
Revises: edfd8047138c
Create Date: 2026-04-04 11:15:37.963633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '670e34926f85'
down_revision: Union[str, Sequence[str], None] = 'edfd8047138c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ia_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_of_ia', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nature_of_entity', sa.String(length=50), nullable=False),
    sa.Column('name_of_entity', sa.String(length=255), nullable=True),
    sa.Column('ia_registration_number', sa.String(length=100), nullable=False),
    sa.Column('date_of_registration', sa.Date(), nullable=False),
    sa.Column('date_of_registration_expiry', sa.Date(), nullable=False),
    sa.Column('registered_address', sa.Text(), nullable=False),
    sa.Column('registered_contact_number', sa.String(length=20), nullable=False),
    sa.Column('office_contact_number', sa.String(length=20), nullable=True),
    sa.Column('registered_email_id', sa.String(length=255), nullable=False),
    sa.Column('cin_number', sa.String(length=100), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bank_branch', sa.String(length=255), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('is_renewal', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('renewal_certificate_no', sa.String(length=100), nullable=True),
    sa.Column('renewal_expiry_date', sa.Date(), nullable=True),
    sa.Column('relationship_manager_id', sa.UUID(), nullable=True),
    sa.Column('ia_certificate_path', sa.String(length=512), nullable=True),
    sa.Column('ia_signature_path', sa.String(length=512), nullable=True),
    sa.Column('ia_logo_path', sa.String(length=512), nullable=True),
    sa.Column('max_client_permit', sa.Integer(), server_default='10', nullable=False),
    sa.Column('current_client_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ia_registration_number')
    )
    op.create_table('contact_persons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ia_master_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ia_master_id'], ['ia_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ia_master_id', sa.UUID(), nullable=False),
    sa.Column('name_of_employee', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('ia_registration_number', sa.String(length=100), nullable=False),
    sa.Column('date_of_registration', sa.Date(), nullable=True),
    sa.Column('date_of_registration_expiry', sa.Date(), nullable=True),
    sa.Column('certificate_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ia_master_id'], ['ia_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_details')
    op.drop_table('contact_persons')
    op.drop_table('ia_master')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
