"""add_compliance_fields_to_clients_final

Revision ID: d2ba705a30b4
Revises: 77846ec918bd
Create Date: 2026-03-12 14:27:14.160323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2ba705a30b4'
down_revision: Union[str, Sequence[str], None] = '77846ec918bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Sanitized: Removed business tables belonging to tenant silo.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Sanitized: Removed business tables belonging to tenant silo.
    pass
    # ### end Alembic commands ###
